# CodeRabbit Configuration for Power Automate Documentation
# This configuration optimizes CodeRabbit's review for Power Automate guides

# Review Settings
reviews:
  # Enable auto-review for all pull requests
  auto_review:
    enabled: true
    # Review drafts to catch issues early
    drafts: true

  # High-level review instructions  
  high_level_summary: true
  
  # Provide detailed feedback
  review_status: true
  
  # Review tools configuration
  tools:
    # Ruff for Python (if any Python scripts are added)
    ruff:
      enabled: false
    
    # Biome for JavaScript/TypeScript (if any scripts are added)
    biome:
      enabled: false
    
    # Hadolint for Docker (if Dockerfiles are added)
    hadolint:
      enabled: false
    
    # yamllint for YAML files
    yamllint:
      enabled: true
    
    # GitLeaks for secrets detection
    gitleaks:
      enabled: true
    
    # Markdownlint for markdown files
    markdownlint:
      enabled: true

  # Review scope - focus on documentation
  path_filters:
    - "**/*.md"
    - "**/*.txt"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"

# Language settings
language: "en-US"

# Chat/conversation settings
chat:
  # Enable conversational reviews
  auto_reply: true

# System settings
system:
  # Improve reviews over time
  learnings:
    scope: "auto"

# Early access features
early_access: false